services:
  mirofish:
    build: .
    # image: ghcr.io/666ghj/mirofish:latest
    # image: ghcr.nju.edu.cn/666ghj/mirofish:latest
    container_name: mirofish
    env_file:
      - .env
    ports:
      - "3003:3000"
      - "5005:5001"
    restart: unless-stopped
    volumes:
      - ./backend/uploads:/app/backend/uploads
      - ./backend/app:/app/backend/app
